server:
  port: 8091
  servlet:
    context-path: /api

spring:
  application:
    name: ExtractFileData

  logging:
    level:
      org.springframework.data.mongodb: debug

  data:
    mongodb:
      host: cluster0.gntk3.mongodb.net
      port: 27017
      uri: mongodb+srv://admin:admin@cluster0.5xindie.mongodb.net/
      username: admin
      password: admin
      authentication-database: admin
      database: extractfiledata

spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

path:
  base: C:\workspace\dpac-offline\enviroment\ipac-offline\offline\volume\bucket