openapi: 3.0.0
info:
  title: Extract Metadata and Thumbnails
  description: Servizio per il salvataggio di metadati e metriche, e generazione di thumbnails per immagini TIFF
  version: 1.0.0
servers:
  - url: http://localhost:9091
    description: Server Locale
components:
  schemas:
    MetadataRequest:
      type: object
      properties:
        path:
          type: string

    MetricheSummary:
      type: object
      properties:
        numRisorse:
          type: integer
        dimTotale:
          type: integer
          format: int64

    DettaglioRisorse:
      type: object
      properties:
        formatoFile:
          type: string
        metricheSummary:
          $ref: "#/components/schemas/MetricheSummary"

    MetricaResponse:
      type: object
      properties:
        codiceCantiere:
          type: string
        codiceLotto:
          type: string
        codicePacchetto:
          type: string
        metricheSummary:
          $ref: "#/components/schemas/MetricheSummary"
        dettagliRisorse:
          type: array
          $ref: "#/components/schemas/DettaglioRisorse"

    MetadatiRisorsaResponse:
      type: object
      properties:
        urlOggetto:
          type: string
        nomeOggetto:
          type: string
        dimensioneFile:
          type: string
        formatoFile:
          type: string
        codiceCantiere:
          type: string
        codiceLotto:
          type: string
        codicePacchetto:
          type: string

paths:
  /metadata/:
    post:
      summary: Crea un nuovo metadata
      operationId: extractMetadata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Metadata"
      responses:
        "201":
          description: Metadati e metriche generate con successo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
        "400":
          description: Richiesta non valida

    delete:
      summary: Elimina tutti i dati dal db
      operationId: deleteAllData
      responses:
        "204":
          description: Tutti i dati eliminati con successo
        "500":
          description: Errore interno del server

  /metrica/:
    get:
      summary: Recupera tutte le metriche
      operationId: getAllMetriche
      responses:
        "200":
          description: Lista delle metriche recuperata con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MetricaResponse"
        "500":
          description: Errore interno del server

  /risorse/:
    get:
      summary: Recupera tutti i metadati
      operationId: getAllRisorse
      responses:
        "200":
          description: Lista delle risorse recuperare con successo
          content:
            application/json:
              schema: